# Generated by Django 4.1.2 on 2022-11-04 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nazwa kategorii')),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa maszyny')),
                ('code', models.CharField(max_length=50, verbose_name='Kod maszyny')),
                ('mth', models.IntegerField(verbose_name='Motogodziny')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data utworzenia')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machine.category', verbose_name='Kategoria')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mth', models.IntegerField(verbose_name='Motogodziny')),
                ('service_type', models.CharField(choices=[('250', '250mth'), ('500', '500mth'), ('1000', '1000mth')], max_length=4, verbose_name='Typ serwisu')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data utworzenia')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mach', to='machine.machine', verbose_name='Kod maszyny')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
